puts "Student Directory - My Makers Academy Cohort"
puts "-------------------"
puts "Mario Gintili"
puts "Mikhail Dubov"
puts "Karolis Noreika"
puts "Michael Sidon"
puts "Charles De Barros"
puts "Ruslan Vikhor"
puts "Toby Retallick"
puts "Mark Mekhaiel"
puts "Sarah Young"
puts "Hannah Wight"
puts "Khushkaran Singh"
puts "Rick brunstedt"
puts "Manjit Singh"
puts "Ross Hepburn"
puts "Tiffanie Chia"
puts "Matthew Thomas"
puts "Freddy McGroarty"
puts "Tyler Rollins"
puts "Richard Curteis"
puts "Anna Yanova"
puts "Andrew Cumine"
puts "Overall, there are 21 awesome students."
